from pathlib import Path
root=Path('/mnt/data/v40work/Sources/ChatApp')
models=root/'MCModels.swift'
s=models.read_text()
old='''struct MCChatHoverItem: Identifiable, Equatable, Codable, Sendable {\n    var id: UUID = UUID()\n    var resourceName: String\n    var displayName: String\n    var count: Int = 1\n    var legacyItemId: Int16? = nil\n    var damage: Int16 = 0\n    var lore: [[MCChatSegment]] = []\n    var enchantments: [String] = []\n    var rawValue: String? = nil\n}'''
new='''struct MCChatHoverItem: Identifiable, Equatable, Codable, Sendable {\n    var id: UUID = UUID()\n    var resourceName: String\n    var displayName: String\n    var count: Int = 1\n    var legacyItemId: Int16? = nil\n    var damage: Int16 = 0\n    var lore: [[MCChatSegment]] = []\n    var enchantments: [String] = []\n    var rawValue: String? = nil\n\n    private enum CodingKeys: String, CodingKey {\n        case id, resourceName, displayName, count, legacyItemId, damage, lore, enchantments, rawValue\n    }\n\n    init(id: UUID = UUID(), resourceName: String, displayName: String, count: Int = 1,\n         legacyItemId: Int16? = nil, damage: Int16 = 0, lore: [[MCChatSegment]] = [],\n         enchantments: [String] = [], rawValue: String? = nil) {\n        self.id = id\n        self.resourceName = resourceName\n        self.displayName = displayName\n        self.count = count\n        self.legacyItemId = legacyItemId\n        self.damage = damage\n        self.lore = lore\n        self.enchantments = enchantments\n        self.rawValue = rawValue\n    }\n\n    init(from decoder: Decoder) throws {\n        let c = try decoder.container(keyedBy: CodingKeys.self)\n        id = try c.decodeIfPresent(UUID.self, forKey: .id) ?? UUID()\n        resourceName = try c.decode(String.self, forKey: .resourceName)\n        displayName = try c.decode(String.self, forKey: .displayName)\n        count = try c.decodeIfPresent(Int.self, forKey: .count) ?? 1\n        legacyItemId = try c.decodeIfPresent(Int16.self, forKey: .legacyItemId)\n        damage = try c.decodeIfPresent(Int16.self, forKey: .damage) ?? 0\n        lore = try c.decodeIfPresent([[MCChatSegment]].self, forKey: .lore) ?? []\n        // v39 and older did not store this field.\n        enchantments = try c.decodeIfPresent([String].self, forKey: .enchantments) ?? []\n        rawValue = try c.decodeIfPresent(String.self, forKey: .rawValue)\n    }\n\n    func encode(to encoder: Encoder) throws {\n        var c = encoder.container(keyedBy: CodingKeys.self)\n        try c.encode(id, forKey: .id)\n        try c.encode(resourceName, forKey: .resourceName)\n        try c.encode(displayName, forKey: .displayName)\n        try c.encode(count, forKey: .count)\n        try c.encodeIfPresent(legacyItemId, forKey: .legacyItemId)\n        try c.encode(damage, forKey: .damage)\n        try c.encode(lore, forKey: .lore)\n        try c.encode(enchantments, forKey: .enchantments)\n        try c.encodeIfPresent(rawValue, forKey: .rawValue)\n    }\n}'''
if old not in s: print('model exact block not found')
else: s=s.replace(old,new)
models.write_text(s)

# Add enchantments to legacy slot parsing as lore-style blue lines.
inv=root/'MCInventory.swift'
s=inv.read_text()
old='''            if let display = root.get("display") {\n                if let name = display.get("Name")?.asString {\n                    // 1.12.2: display.Name là chuỗi thô kiểu cũ, có thể chứa mã màu §.\n                    displayNameSegments = chatSegments(from: name)\n                }\n                if let lore = display.get("Lore")?.asStringList {\n                    loreSegments = lore.map { chatSegments(from: $0) }\n                }\n            }'''
new='''            if let display = root.get("display") {\n                if let name = display.get("Name")?.asString {\n                    // 1.12.2: display.Name là chuỗi thô kiểu cũ, có thể chứa mã màu §.\n                    displayNameSegments = chatSegments(from: name)\n                }\n                if let lore = display.get("Lore")?.asStringList {\n                    loreSegments = lore.map { chatSegments(from: $0) }\n                }\n            }\n            if let enchantments = enchantmentLines(from: root.get("Enchantments")) {\n                loreSegments.append(contentsOf: enchantments)\n            }'''
if old not in s: print('inventory parse block not found')
else: s=s.replace(old,new)
# Add helper before MARK slot data.
needle='''// MARK: - Slot data (định dạng pre-1.13 dùng bởi protocol 340 / 1.12.2)'''
helper='''private func enchantmentLines(from node: MCNBT?) -> [[MCChatSegment]]? {\n    guard case .list(let values) = node else { return nil }\n    var lines: [[MCChatSegment]] = []\n    for value in values {\n        guard case .compound(let dict) = value,\n              case .string(let rawID)? = dict["id"] else { continue }\n        let lvl: Int = {\n            if case .short(let n)? = dict["lvl"] { return Int(n) }\n            if case .int(let n)? = dict["lvl"] { return Int(n) }\n            if case .byte(let n)? = dict["lvl"] { return Int(n) }\n            return 1\n        }()\n        let id = rawID.replacingOccurrences(of: "minecraft:", with: "")\n        let name = id.replacingOccurrences(of: "_", with: " ")\n            .split(separator: " ")\n            .map { $0.prefix(1).uppercased() + $0.dropFirst() }\n            .joined(separator: " ")\n        let roman: String\n        switch lvl { case 1: roman = "I"; case 2: roman = "II"; case 3: roman = "III"; case 4: roman = "IV"; case 5: roman = "V"; default: roman = String(lvl) }\n        lines.append([MCChatSegment(text: "\\(name) \\(roman)", colorHex: "#5555FF")])\n    }\n    return lines\n}\n\n'''
s=s.replace(needle,helper+needle)
inv.write_text(s)

# Patch chat hover URL encode/decode enchantments.
chat=root/'MCChatView.swift'
s=chat.read_text()
s=s.replace('''        "damage": Int(item.damage),\n        "lore": item.lore.map { line in''','''        "damage": Int(item.damage),\n        "enchantments": item.enchantments,\n        "lore": item.lore.map { line in''')
s=s.replace('''    let legacy = (object["legacyItemId"] as? Int).map(Int16.init)\n    var lore: [[MCChatSegment]] = []''','''    let legacy = (object["legacyItemId"] as? Int).map(Int16.init)\n    let enchantments = object["enchantments"] as? [String] ?? []\n    var lore: [[MCChatSegment]] = []''')
s=s.replace('''    return MCChatHoverItem(resourceName: resourceName, displayName: displayName, count: count, legacyItemId: legacy, damage: damage, lore: lore, rawValue: object["rawValue"] as? String)''','''    return MCChatHoverItem(resourceName: resourceName, displayName: displayName, count: count, legacyItemId: legacy, damage: damage, lore: lore, enchantments: enchantments, rawValue: object["rawValue"] as? String)''')
chat.write_text(s)
print('patch2 done')
