from pathlib import Path

root=Path('/mnt/data/v40work/Sources/ChatApp')
mcchat=root/'MCChatView.swift'
mcclient=root/'MCClient.swift'
models=root/'MCModels.swift'
plist=root/'Info.plist'

s=mcchat.read_text()
# Direct ellipsis -> tooltip instead of action sheet for GUI and inventory.
s=s.replace('''            // ... vẫn mở menu nâng cao: Display lore / Left click / Right click / Drop all.\n            Button {\n                reliableActionTitle = item.plainName\n                reliableActionWindowItem = item\n                reliableActionInventorySlot = nil\n                showReliableItemActionSheet = true\n            } label: {''','''            // Một chạm vào ... mở tooltip/lore ngay, không mở menu trung gian.\n            Button {\n                tooltipWindowItem = item\n            } label: {''')
s=s.replace('''                            Button {\n                                reliableActionTitle = client.playerInventory[slot]?.plainName ?? "Item actions"\n                                reliableActionWindowItem = nil\n                                reliableActionInventorySlot = slot\n                                showReliableItemActionSheet = true\n                            } label: {''','''                            Button {\n                                tooltipItem = client.playerInventory[slot]\n                            } label: {''')
# Update chat hover sheet to show display + enchantments + lore.
old='''                    VStack(alignment: .leading, spacing: 3) {\n                        Text(item.displayName)\n                            .font(.headline)\n                            .foregroundStyle(.white)\n                        Text("×\\(item.count)")\n                            .font(.subheadline.monospacedDigit().weight(.semibold))\n                            .foregroundStyle(.secondary)\n                    }\n                }\n                Text(item.resourceName)\n                    .font(.caption.monospaced())\n                    .foregroundStyle(.secondary)\n                Divider().overlay(Color.white.opacity(0.12))\n                if item.lore.isEmpty {\n                    Text("Không có Lore")\n                        .foregroundStyle(.secondary)\n                } else {\n                    ForEach(Array(item.lore.enumerated()), id: \\.offset) { _, line in\n                        coloredText(line)\n                    }\n                }'''
new='''                    VStack(alignment: .leading, spacing: 3) {\n                        Text(item.displayName)\n                            .font(.headline)\n                            .foregroundStyle(.white)\n                        Text("×\\(item.count)")\n                            .font(.subheadline.monospacedDigit().weight(.semibold))\n                            .foregroundStyle(.secondary)\n                    }\n                }\n                Text(item.resourceName)\n                    .font(.caption.monospaced())\n                    .foregroundStyle(.secondary)\n                Divider().overlay(Color.white.opacity(0.12))\n                if !item.enchantments.isEmpty {\n                    Text("Enchantments")\n                        .font(.subheadline.weight(.semibold))\n                        .foregroundStyle(.white)\n                    ForEach(Array(item.enchantments.enumerated()), id: \\.offset) { _, line in\n                        Text(line)\n                            .font(.system(size: 15, weight: .medium))\n                            .foregroundStyle(.blue)\n                    }\n                }\n                if item.lore.isEmpty {\n                    Text("Không có Lore")\n                        .foregroundStyle(.secondary)\n                } else {\n                    ForEach(Array(item.lore.enumerated()), id: \\.offset) { _, line in\n                        coloredText(line)\n                    }\n                }'''
if old not in s:
    print('chat hover block not found')
else:
    s=s.replace(old,new)
mcchat.write_text(s)

# Add enchantments to model.
s=models.read_text()
s=s.replace('''    var damage: Int16 = 0\n    var lore: [[MCChatSegment]] = []\n    var rawValue: String? = nil''','''    var damage: Int16 = 0\n    var lore: [[MCChatSegment]] = []\n    var enchantments: [String] = []\n    var rawValue: String? = nil''')
models.write_text(s)

# Patch client parser + background behavior.
s=mcclient.read_text()
s=s.replace('''    private var enteredBackgroundAt: Date?\n    /// true sau khi người dùng bấm Kết nối; khi mạng chập chờn/iOS trả POSIX 53,''','''    private var enteredBackgroundAt: Date?\n    private var isAppInBackground = false\n    private var pendingBackgroundNetworkFailure: String?\n    /// true sau khi người dùng bấm Kết nối; khi mạng chập chờn/iOS trả POSIX 53,''')
# Replace background observers method body content with no-audio, delayed recovery.
start=s.index('    private func setupBackgroundObservers() {')
end=s.index('    // MARK: - Kết nối', start)
new_method='''    private func setupBackgroundObservers() {\n        let nc = NotificationCenter.default\n        backgroundObservers.append(nc.addObserver(forName: UIApplication.didEnterBackgroundNotification, object: nil, queue: .main) { [weak self] _ in\n            Task { @MainActor [weak self] in\n                guard let self else { return }\n                self.isAppInBackground = true\n                self.enteredBackgroundAt = Date()\n                // Không phát audio giả và không gửi heartbeat/movement khi app xuống nền.\n                // iOS có thể tạm dừng TCP; để socket chết tự nhiên thay vì tạo lỗi POSIX 89\n                // ngay lập tức và hiện banner giống một packet send lỗi.\n                self.stopWatchdog()\n                self.stopIdleAliveTicker()\n                BackgroundKeepAlive.shared.stop()\n            }\n        })\n        backgroundObservers.append(nc.addObserver(forName: UIApplication.willEnterForegroundNotification, object: nil, queue: .main) { [weak self] _ in\n            Task { @MainActor [weak self] in\n                guard let self else { return }\n                self.isAppInBackground = false\n                let backgroundDuration = self.enteredBackgroundAt.map { Date().timeIntervalSince($0) } ?? 0\n                self.enteredBackgroundAt = nil\n                BackgroundKeepAlive.shared.stop()\n\n                guard self.shouldStayConnected else { return }\n                // Chỉ xác định socket đã chết sau khi quay lại foreground.\n                // Không coi việc vừa rời app là disconnect tức thời.\n                let silentFor = Date().timeIntervalSince(self.lastPacketReceivedAt)\n                if self.pendingBackgroundNetworkFailure != nil || self.connection == nil ||\n                    (self.state == .connected && (backgroundDuration >= 10 && silentFor >= 10)) {\n                    let reason = self.pendingBackgroundNetworkFailure ?? "socket không còn khả dụng sau khi app chạy nền"\n                    self.pendingBackgroundNetworkFailure = nil\n                    self.appendLog(.error, "Lỗi kết nối: The operation couldn’t be completed. (Network.NWError error 89 - Operation canceled by system/peer). \\(reason)")\n                    self.scheduleReconnect(reason: "socket stale sau khi quay lại app")\n                } else if self.state == .connected {\n                    self.startWatchdog()\n                    self.startIdleAliveTicker()\n                } else if self.state != .connecting && self.state != .loggingIn {\n                    self.scheduleReconnect(reason: "quay lại ứng dụng")\n                }\n            }\n        })\n    }\n\n'''
s=s[:start]+new_method+s[end:]
# Send completion: suppress background errors; report ChatCraft-like foreground message.
s=s.replace('''                    if let error {\n                    Task { @MainActor [weak self] in\n                        guard let self else { return }\n                        if case .posix(let posix) = error, posix.rawValue == 89, !self.shouldStayConnected { return }\n                        self.appendLog(.error, "Gửi packet thất bại: \\(error.localizedDescription)\\(self.networkErrorHint(error))")\n                        if self.shouldStayConnected, self.state != .connecting, self.state != .loggingIn {\n                            self.scheduleReconnect(reason: "send packet lỗi")\n                        }\n                    }\n                }''','''                    if let error {\n                    Task { @MainActor [weak self] in\n                        guard let self else { return }\n                        if self.isAppInBackground {\n                            self.pendingBackgroundNetworkFailure = error.localizedDescription\n                            return\n                        }\n                        self.appendLog(.error, self.chatCraftNetworkErrorMessage(error))\n                        if self.shouldStayConnected, self.state != .connecting, self.state != .loggingIn {\n                            self.scheduleReconnect(reason: "send packet lỗi")\n                        }\n                    }\n                }''')
s=s.replace('''                guard let error else { return }\n                // NWConnection reports ECANCELED for packets that were already queued\n                // when we intentionally cancel a stale socket. That is not a new root\n                // cause and must not recursively trigger another reconnect.\n                if case .posix(let posix) = error, posix.rawValue == 89, !self.shouldStayConnected {\n                    return\n                }\n                self.appendLog(.error, "Gửi packet thất bại: \\(error.localizedDescription)\\(self.networkErrorHint(error))")\n                if self.shouldStayConnected, self.state != .connecting, self.state != .loggingIn {\n                    self.scheduleReconnect(reason: "send packet lỗi")\n                }''','''                guard let error else { return }\n                if self.isAppInBackground {\n                    self.pendingBackgroundNetworkFailure = error.localizedDescription\n                    return\n                }\n                self.appendLog(.error, self.chatCraftNetworkErrorMessage(error))\n                if self.shouldStayConnected, self.state != .connecting, self.state != .loggingIn {\n                    self.scheduleReconnect(reason: "send packet lỗi")\n                }''')
# Add helper.
needle='''    private func networkErrorHint(_ error: NWError) -> String {'''
insert='''    private func chatCraftNetworkErrorMessage(_ error: NWError) -> String {\n        if case .posix(let posix) = error {\n            let detail: String\n            switch posix.rawValue {\n            case 89: detail = "Operation canceled by system/peer"\n            case 53: detail = "Connection reset by peer"\n            default: detail = posix.description\n            }\n            return "Lỗi kết nối: The operation couldn’t be completed. (Network.NWError error \\(posix.rawValue) - \\(detail))"\n        }\n        return "Lỗi kết nối: The operation couldn’t be completed. (\\(error.localizedDescription))"\n    }\n\n'''
s=s.replace(needle,insert+needle)
# Receive loop background delay.
old='''                if let error {\n                    self.dumpProtocolTrace(trigger: "NWConnection error: \\(error.localizedDescription)")\n                    self.appendLog(.error, "Mất kết nối: \\(error.localizedDescription)\\(self.networkErrorHint(error))")\n                    self.shouldStayConnected = false\n                    self.reconnectWorkItem?.cancel()\n                    self.reconnectWorkItem = nil\n                    self.clearCurrentChatMessagesPreservingDebug()\n                    self.state = .failed(error.localizedDescription)\n                    return\n                }'''
new='''                if let error {\n                    self.dumpProtocolTrace(trigger: "NWConnection error: \\(error.localizedDescription)")\n                    if self.isAppInBackground {\n                        self.pendingBackgroundNetworkFailure = error.localizedDescription\n                        self.connection = nil\n                        self.stopWatchdog()\n                        self.stopIdleAliveTicker()\n                        // Giữ phiên logic và UI yên cho tới khi người dùng quay lại app.\n                        // Đây là điểm quan trọng để không hiện disconnect ngay lúc Home/đổi app.\n                        return\n                    }\n                    self.appendLog(.error, self.chatCraftNetworkErrorMessage(error))\n                    self.shouldStayConnected = false\n                    self.reconnectWorkItem?.cancel()\n                    self.reconnectWorkItem = nil\n                    self.clearCurrentChatMessagesPreservingDebug()\n                    self.state = .failed(error.localizedDescription)\n                    return\n                }'''
if old not in s: print('receive error block not found')
else: s=s.replace(old,new)
# On TCP EOF while background, also defer.
old='''                if isComplete {\n                    if self.state != .disconnected {\n                        self.dumpProtocolTrace(trigger: "TCP EOF / server đóng socket (không có Disconnect packet trước EOF)")\n                        self.appendLog(.error, "Server đã đóng kết nối.")\n                        self.shouldStayConnected = false\n                        self.reconnectWorkItem?.cancel()\n                        self.reconnectWorkItem = nil\n                        self.clearCurrentChatMessagesPreservingDebug()\n                        self.state = .disconnected\n                    }\n                    return\n                }'''
new='''                if isComplete {\n                    if self.state != .disconnected {\n                        self.dumpProtocolTrace(trigger: "TCP EOF / server đóng socket (không có Disconnect packet trước EOF)")\n                        if self.isAppInBackground {\n                            self.pendingBackgroundNetworkFailure = "TCP EOF / server đóng socket"\n                            self.connection = nil\n                            self.stopWatchdog()\n                            self.stopIdleAliveTicker()\n                            return\n                        }\n                        self.appendLog(.error, "Lỗi kết nối: The operation couldn’t be completed. (TCP EOF - server đóng socket)")\n                        self.shouldStayConnected = false\n                        self.reconnectWorkItem?.cancel()\n                        self.reconnectWorkItem = nil\n                        self.clearCurrentChatMessagesPreservingDebug()\n                        self.state = .disconnected\n                    }\n                    return\n                }'''
if old not in s: print('eof block not found')
else: s=s.replace(old,new)
# remove automatic background audio startup remnants in comments? keep class but unused. Remove Info.plist audio mode.
plist_s=plist.read_text()
import re
plist_s=re.sub(r'\n    <key>UIBackgroundModes</key>\n    <array>\n.*?\n    </array>', '', plist_s, flags=re.S)
plist.write_text(plist_s)

# Add enchantment parser to parseHoverItemObject return and legacy parser.
old='''    var lore: [[MCChatSegment]] = []\n    if let tag = obj["tag"] as? [String: Any],\n       let display = tag["display"] as? [String: Any] {'''
new='''    var lore: [[MCChatSegment]] = []\n    var enchantments: [String] = []\n    if let tag = obj["tag"] as? [String: Any] {\n        enchantments = parseEnchantments(tag["Enchantments"])\n    }\n    if let components = obj["components"] as? [String: Any], enchantments.isEmpty {\n        enchantments = parseEnchantments(components["minecraft:enchantments"])\n    }\n    if let tag = obj["tag"] as? [String: Any],\n       let display = tag["display"] as? [String: Any] {'''
s=s.replace(old,new)
s=s.replace('''    return MCChatHoverItem(resourceName: "minecraft:\\(resourceName)", displayName: displayName,\n                           count: count, legacyItemId: legacy, damage: damage, lore: lore, rawValue: nil)''','''    return MCChatHoverItem(resourceName: "minecraft:\\(resourceName)", displayName: displayName,\n                           count: count, legacyItemId: legacy, damage: damage, lore: lore,\n                           enchantments: enchantments, rawValue: nil)''')
# raw JSON string wrapper needs propagate enchantments automatically via object copy
s=s.replace('''            return MCChatHoverItem(resourceName: item.resourceName, displayName: item.displayName,\n                                   count: item.count, legacyItemId: item.legacyItemId, damage: item.damage,\n                                   lore: item.lore, rawValue: rawValue)''','''            return MCChatHoverItem(resourceName: item.resourceName, displayName: item.displayName,\n                                   count: item.count, legacyItemId: item.legacyItemId, damage: item.damage,\n                                   lore: item.lore, enchantments: item.enchantments, rawValue: rawValue)''')
# legacy hover parser add regex for enchantments.
old='''    var displayName = friendlyItemName(resourceName)\n    var lore: [[MCChatSegment]] = []'''
new='''    var displayName = friendlyItemName(resourceName)\n    var lore: [[MCChatSegment]] = []\n    var enchantments: [String] = []'''
# only first occurrence after parseLegacy? There are two. Use replace last occurrence by slicing.
pos=s.find('private func parseLegacyHoverItemString')
pre=s[:pos]; post=s[pos:]
post=post.replace(old,new,1)
oldret='''    return MCChatHoverItem(resourceName: "minecraft:\\(resourceName)", displayName: displayName,\n                           count: count, legacyItemId: legacyItemID(for: resourceName), damage: damage,\n                           lore: lore, rawValue: raw)'''
newret='''    // NBT string dạng 1.12: Enchantments:[{id:"minecraft:sharpness",lvl:5s}, ...]\n    if let enchRegex = try? NSRegularExpression(pattern: #"Enchantments\\s*[:=]\\s*\\[([^\\]]*)\\]"#),\n       let em = enchRegex.firstMatch(in: raw, range: NSRange(raw.startIndex..., in: raw)),\n       let er = Range(em.range(at: 1), in: raw) {\n        let body = String(raw[er])\n        if let one = try? NSRegularExpression(pattern: #"id\\s*[:=]\\s*[\\\"']?([A-Za-z0-9_:\\-.]+)[\\\"']?[^{}]*?lvl\\s*[:=]\\s*(-?\\d+)"#) {\n            for m in one.matches(in: body, range: NSRange(body.startIndex..., in: body)) {\n                guard let ir = Range(m.range(at: 1), in: body), let lr = Range(m.range(at: 2), in: body) else { continue }\n                let id = String(body[ir]).replacingOccurrences(of: "minecraft:", with: "")\n                let lvl = Int(body[lr]) ?? 1\n                enchantments.append("\\(friendlyEnchantmentName(id)) \\(romanNumeral(lvl))")\n            }\n        }\n    }\n    return MCChatHoverItem(resourceName: "minecraft:\\(resourceName)", displayName: displayName,\n                           count: count, legacyItemId: legacyItemID(for: resourceName), damage: damage,\n                           lore: lore, enchantments: enchantments, rawValue: raw)'''
post=post.replace(oldret,newret,1)
s=pre+post
# Add helper functions before friendlyItemName.
needle='''private func friendlyItemName(_ resourceName: String) -> String {'''
helpers='''private func parseEnchantments(_ value: Any?) -> [String] {\n    guard let arr = value as? [Any] else { return [] }\n    var result: [String] = []\n    for element in arr {\n        if let dict = element as? [String: Any] {\n            let rawID = (dict["id"] as? String) ?? (dict["Id"] as? String) ?? ""\n            let rawLevel: Int = {\n                if let n = dict["lvl"] as? NSNumber { return n.intValue }\n                if let n = dict["level"] as? NSNumber { return n.intValue }\n                if let s = dict["lvl"] as? String { return Int(s) ?? 1 }\n                return 1\n            }()\n            let id = rawID.replacingOccurrences(of: "minecraft:", with: "")\n            guard !id.isEmpty else { continue }\n            result.append("\\(friendlyEnchantmentName(id)) \\(romanNumeral(rawLevel))")\n        }\n    }\n    return result\n}\n\nprivate func friendlyEnchantmentName(_ id: String) -> String {\n    let key = id.replacingOccurrences(of: "_", with: " ")\n    return key.split(separator: " ").map { $0.prefix(1).uppercased() + $0.dropFirst() }.joined(separator: " ")\n}\n\nprivate func romanNumeral(_ number: Int) -> String {\n    if number <= 0 { return "I" }\n    let values: [(Int, String)] = [(1000,"M"),(900,"CM"),(500,"D"),(400,"CD"),(100,"C"),(90,"XC"),(50,"L"),(40,"XL"),(10,"X"),(9,"IX"),(5,"V"),(4,"IV"),(1,"I")]\n    var n = number\n    var out = ""\n    for (v, s) in values {\n        while n >= v { out += s; n -= v }\n    }\n    return out\n}\n\n'''
s=s.replace(needle,helpers+needle)
mcclient.write_text(s)

print('patched')
