name: ChatMC Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-15

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Check source
      run: |
        pwd
        ls -la
        find . -name "project.yml"

    - name: Install XcodeGen
      run: |
        brew install xcodegen

    - name: Generate Xcode Project
      run: |
        xcodegen generate
        ls -la
        test -d Minecraft.xcodeproj

    - name: Archive
      run: |
        xcodebuild archive \
        -project Minecraft.xcodeproj \
        -scheme Minecraft \
        -archivePath build/Minecraft.xcarchive \
        -sdk iphoneos \
        -destination generic/platform=iOS \
        CODE_SIGNING_ALLOWED=NO \
        CODE_SIGNING_REQUIRED=NO
